name: Build


on:
  push:
    branches:
    - '**'
    - '!dev'
    tags:
    - '**'
    - '!v[0-9]+.[0-9]+.[0-9]+'
    - '!v[0-9]+.[0-9]+.[0-9]+\+*'
    - '!v[0-9]+.[0-9]+.[0-9]+-*'
    - '!latest-dev'
  pull_request:
    branches:
    - '**'


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    -
      name : Checkout
      uses : actions/checkout@v3
    -
      name : Build artifacts
      uses : ./.github/actions/build
